apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: recipe-app
data:
  MONGO_URI: mongodb://mongo-0.mongo.recipe-app.svc.cluster.local:27017,mongo-1.mongo.recipe-app.svc.cluster.local:27017,mongo-2.mongo.recipe-app.svc.cluster.local:27017/?replicaSet=rs0