apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
  namespace: recipe-app
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:7
        command:
          - bash
          - -c
          - |
            echo "Waiting for MongoDB to be ready..."
            until mongosh --host mongo-0.mongo.recipe-app.svc.cluster.local --eval "db.adminCommand('ping')" &>/dev/null; do sleep 2; done

            echo "Initiating replica set..."
            mongosh --host mongo-0.mongo.recipe-app.svc.cluster.local <<EOF
            rs.initiate({
              _id: "rs0",
              members: [
                { _id: 0, host: "mongo-0.mongo.recipe-app.svc.cluster.local:27017" },
                { _id: 1, host: "mongo-1.mongo.recipe-app.svc.cluster.local:27017" },
                { _id: 2, host: "mongo-2.mongo.recipe-app.svc.cluster.local:27017" }
              ]
            })
            EOF
      restartPolicy: OnFailure