name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_BACKEND: recipe_backend
      IMAGE_FRONTEND: recipe_frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Backend Docker image
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_BACKEND:latest ./backend

      - name: Build Frontend Docker image
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_FRONTEND:latest ./frontend

      - name: Push Backend image
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_BACKEND:latest

      - name: Push Frontend image
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_FRONTEND:latest
